-- 코드를 입력하세요
SELECT UGU.USER_ID, UGU.NICKNAME, CONCAT(UGU.CITY, ' ', UGU.STREET_ADDRESS1, ' ', UGU.STREET_ADDRESS2),
        CONCAT(LEFT(UGU.TLNO, 3), '-', MID(UGU.TLNO, 4, 4), '-', RIGHT(UGU.TLNO, 4))
FROM USED_GOODS_BOARD AS UGB
JOIN USED_GOODS_USER AS UGU ON UGB.WRITER_ID = UGU.USER_ID
GROUP BY UGU.USER_ID
HAVING COUNT(UGU.USER_ID) >= 3
ORDER BY UGU.USER_ID DESC
